server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: product
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/product/**
        - id: category
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/category/**
      globalcors:  # Add this section for CORS configuration
        corsConfiguration:
          allowedOrigins:  # Replace with your allowed origins (e.g., http://localhost:4200)
            - "*"  # For development only, replace with specific origins in production
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
          allowedHeaders:
            - Content-Type
            - Authorization
          allowCredentials: true
          maxAge: 3600
  eureka:
    client:
      register-with-eureka: false
